apiVersion: v1
kind: Service
metadata:
  name: db-clustersvc
  namespace: sqldb
  labels:
    app.kubernetes.io/name: sqldb
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app.kubernetes.io/name: sqldb