apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldb-deployment
  namespace: sqldb
  labels:
    app: mysql
    component: backend
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        component: backend
    spec:
      containers:
      - name: sqldb
        image: 796109909635.dkr.ecr.us-east-1.amazonaws.com/jculloa-ecr:mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass123