apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  namespace: webapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
        app: employees
        version: v1
  template:
    metadata:
        labels:
            app: employees
            version: v1
    spec:
      containers:
      - name: webapp
        image: 796109909635.dkr.ecr.us-east-1.amazonaws.com/jculloa-ecr:app
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: db-clustersvc.sqldb.svc.cluster.local
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: pass123