apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: webapp
spec:
  containers:
  - name: webapp
    image: 796109909635.dkr.ecr.us-east-1.amazonaws.com/jculloa-ecr:app
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: 10.244.0.7
    - name: DBPORT
      value: "3306"
    - name: DBPWD
      valueFrom:
        secretKeyRef:
          name: sqlpass
          key: sqlpasswd